### ISSUE TITLE
Data synchronization problems.

### ISSUE THREAD

**Issue by Assert1** [krpc/krpc#357]
I am implementing a tool that computes some maneuver nodes for orbit and body transferts. Everyting works good, except some problems with precision. For example, 2 node transfert from Mun to low Kerbin orbit produce a +-2 km errors at Ap and Pe.

This is not a my computation problems, i am checked maneuvers result with independent integration and have a precision of 2 meters even with 32 bit floats. This is not a KSP problems itself, because i can fix this errors by hands on the created nodes.  So, we are loosing precision somewhere in kRPC. And i have some ideas about where it is, because when i am increasing time scale, precision errors rises rapidly, and can reach hundreeds of kilometers in example case.

Vessel or body orbits are defined by some geometrical parameters that is not changing in time, and eccentric anomaly that is a function of time. But there is no way to get time value (to use it in future as refernece for creating maneuvering nodes) and eccentric anomaly at the _same_ time. We always have some delay between this values even when using streams. KSP physics frame change and stream values update can occur between of two calls to get time and orbit eccentric anomaly. Same thing for position/velocity pair, there is no way to get consistent values in all cases. For example we can have position and time from previous KSP frame, and velocity from next.

So, think we need to make some kind of synchronization between KSP physics frames, and values in client to make get calls consistent. May be suspend and cache values of future frames in streams after calling some function on client (client.lock), and update as usual after calling another function (client.unlock).

**Comment by djungelorm** [comment]
Makes sense. Might also explain the inaccuracies I see in my orbit code unit tests!

The batched RPCs feature in the upcoming v0.4.0 (#325) might help a bit with this. It will allow you to execute a batch of RPCs all in one go, so they will all be executed in the same FixedUpdate.

However, are you wanting to download orbital parameters, then create a maneuver node (based on that data) all in one FixedUpdate? If so then we would indeed need some additional synchronization. Maybe we could add something like:

```python
conn = krpc.connect()
...
conn.start_transaction()
apoapsis = vessel.orbit.apoapsis
...
vessel.control.add_node(...)
conn.end_transaction()
```

When `start_transaction` is called, kRPC will receive and processes RPCs in a single FixedUpdate call until the next `end_transaction`. This essentially pauses the physics (and graphics) updates until the end of the transaction.

There would be a few issues to work out with this but I think it should work:
 * What about other client connections? We should be able to just continue processing them as usual.
 * What if you create a transaction in a transaction?
 * Make sure transactions are ended when a client disconnects, so the game doesn't hang.
 * Would need to make people aware that using these could cause horrific framerates - e.g. repeatedly executing a long-lived transaction.

**Comment by Assert1** [comment]
I think interrupting server side is a very bad idea, because some clients needs continiously synchronized data for each frame (attitude control for example), and this will cause a huge FPS drop. Strict syncronization is not required there, only data integrity (all fetched values must be from one physics frame). This is a key thing. We are leaving network delays as is (KSP freez by ping delay is a very-very bad idea), and focusing only on the data integrity, that is an origin of this problems. From my point of view, the best solution is to chache streamed values on the client side, so each pice of data have a frame id stamp. Calling lock on the client makes all streams synchronized to the latest frame by waiting for values that is not up to date and not updating newer than current frame id values cheacheing it for later use.

Currently, i am end up with a very simple architecture of the clients:
```
while(!finished)
{
	float64 t=ut_stream();
	float64 step=(t-time);
	if(!step)
	{
		// frame is not changed, skip cycle
		CThread::Idle();
		continue;
	};
	time=t;

	... // fetch streams to local variables here
	... // perform some work with updated values
	... // set new values in kRPC objects if required
};
```
So, i am already using some kind of lock to test for frame change. With build in clean lock it will be looks like:
```
while(!finished)
{
	client.lock(); // waits for complete values update for latest recived frame of all streams
	float64 t=ut_stream();
	float64 step=(t-time);
	time=t;

	... // fetch streams to local variables here
	client.unlock(); // now stream values can be updated (from previously chached values during lock, or as soon as recived from the server)
	... // perform some work with updated values
	... // set new values in kRPC objects if required
};
```

I made some investigation of the node creation problems, it is not only about data integrity on the client side. I made a workaround using eccentric_anomaly_at_ut function to sync at current frame, this helps alot (now i can get cosistent orbits data) but i still have some problems. For Planet->Moon transitions, errors now in meters, but for interplanetary transitions, errors still very huge, hundreeds of km. My own conics integration of nodes from original orbit in 64 bit floats results a 1e-5 meters error. So precision lost occurs because of orbits data, or because of node creation process inside kRPC. I have no ideas how to vercome this.

**Comment by Assert1** [comment]
As i can see, precision losses accurs in two places:
1. control.add_node itself, uses floats for speed instead of doubles.
2. I am computing burn vectors in body's non rotation frame coordinates, And then using source orbit velocity vector(computed by myself) at burn time to construct prograde, normal and radial projections... and may be KSP computes this base velocity vector in a slightly different way during reverse operation, or something else... so, my burn_vector is not equals strictly to returned by kRPC.

I am created node with:
DV: X=-672.1886571, Y=-886.6499600, Z=980.3603916 : P=1188.5365726, N=-886.8330302, R=0.4814369
But when i am reading it back, i have:
DV: X=-672.1389335, X=-886.6498384, X=980.3946315 : P=1188.5366211, N=-886.8330078, R=0.4814369
Looks like XYZ is reversed from PNR with other base vector.

**Comment by djungelorm** [comment]
I'll change control.add_node to use doubles.

And I see what you mean about client lock being useful. Essentially just pauses the client from applying stream update messages so would be a simple change to the C++ client library. If you like I can put together a version with this feature added for you to try out?

~~I'm still also worried about the use case in my previous comment - which is orthogonal to the two issues you highlight. If you get orbital data from one physics frame to compute a maneuver node, then create the maneuver node in a subsequent physics frame this would surely introduce some errors in the maneuver, as it is created at a slightly later point in the vessels orbit? In this use case you'd want to get the orbital data and create the maneuver node in the same physics tick - i.e. would need to 'pause' physics during this period.~~ Actually I've realised this is not an issue, as nodes are always created at a time in the future. There might be other cases where this would be a problem, but I guess it doesn't apply in this case. Consider the transactions idea scrapped (for now!)

**Comment by djungelorm** [comment]
As for the node creation, kRPC simply calls the KSP API. So the inaccuracies when reading the node values back is probably something messed up in the KSP API :( I'll do some testing and see what I can figure out.

The node creation code is here:
https://github.com/krpc/krpc/blob/master/service/SpaceCenter/src/Services/Node.cs#L26

**Comment by Assert1** [comment]
>just pauses the client from applying stream update messages
Not just a pause, but waiting for everyting will be updated up to current frame. This is a key thing. At the time of lock, some values stored in the streams are from previous frame, and some from latest, so we need to inhibit future updates on newer values, and still update old values to sync everyting to one frame.

Lock function needs to:
1. Determine latest frame number (latest frame number that was recived by any stream).
2. Redirect stream updates that already have values for determined frame number to some chache.
3. Wait for other streams are updated to determined frame number and redirect updates to chache too.
4. Return to user code.

Unlock function needs to:
1. Update values of streams from it's chache.
2. Redirect all streams updates to direct updates as usual.

**Comment by Assert1** [comment]
And i made some changes to stream class for default constructor support and other operators.
[stream.txt](https://github.com/krpc/krpc/files/533507/stream.txt)
It will be cool to include it in next release.

**Comment by djungelorm** [comment]
Here's a build with the locking and double precision maneuver nodes implemented: 
https://krpc.s3.amazonaws.com/deploy/feature/stream-freezing/719.1/krpc-0.3.6-4-gf5101b4.zip

This is based off of v0.3.6, so is compatible with KSP 1.1.3.

I've renamed `lock()` and `unlock()`to `freeze_streams()` and `thaw_streams()`. As this isn't really locking in the traditional sense, I wanted to call it something different to avoid confusion, and I think this naming is a bit more descriptive of what's actually going on.

The part of the stream update thread that implements freezing is here:
https://github.com/krpc/krpc/blob/feature/stream-freezing/client/cpp/src/stream_manager.cpp#L44

Your suggested implementation is actually more complex than needed. There is a background thread that receives stream update messages from the server. Each message received contains the new values for *all* streams from a *single* physics tick. After it receives an update message, the background thread updates each stream object individually (by locking it and setting the value) so its from this update loop that the synchronization issues arise.

With this in mind, the implementation of freezing/thawing is as follows:

freeze_streams:
 * Notify the update thread that it should freeze updates
 * Wait for the update thread to report that it has frozen
 * When the update thread receives a freeze request it:
  * Receives the next update message
  * Applies the update to all the streams
  * The streams are now in a state where they all have a value from the same physics tick
  * Notifies the `freeze_streams()` call that it has frozen - which causes `freeze_streams()` to return
  * Enters a loop where it receives but ignores each update message

thaw_streams:
 * Notify the update thread that it should unfreeze
 * Wait for the update thread to report that it has thawed
 *  When the update thread receives a thaw notification it:
  * Exits the loop where it's receiving but ignoring updates
  * Applies the last received update message to all streams
  * The streams are now updated with a recent value - so stale values won't be read after thaw_streams returns
  * Notifies `thaw()` that it has resumed updates - which causes `thaw_streams()` to return

Re. the addition of `operator=` - what's the use case for this? Could you open a separate issue for this to keep this thread on topic? Thanks!

**Comment by Assert1** [comment]
Using this build:
- works without freez/thaw
- unhandled exception in some kRPC service thread few ms after streams_thaw
Stack tace:
```
LaunchControl.exe!thread_start<unsigned int (__stdcall*)(void *)>	LaunchControl.exe!issue_debug_notification	Normal
LaunchControl.exe!issue_debug_notification(const wchar_t * const message) Line 125	 
LaunchControl.exe!__acrt_report_runtime_error(const wchar_t * message) Line 142	 
LaunchControl.exe!abort() Line 51	 
LaunchControl.exe!terminate() Line 59	 
[External Code]
[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]	 
LaunchControl.exe!krpc::decoder::decode(google::protobuf::Message & message, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & data, krpc::Client * client) Line 90	 
LaunchControl.exe!krpc::StreamManager::update_thread_main::__l2::<lambda>(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & data) Line 21	 
LaunchControl.exe!krpc::StreamManager::update_thread_main(krpc::StreamManager * stream_manager, const std::shared_ptr<krpc::Connection> & connection, const std::shared_ptr<std::atomic<bool> > & stop, const std::shared_ptr<std::atomic<bool> > & should_freeze, const std::shared_ptr<std::atomic<bool> > & frozen) Line 42	 
[External Code]
LaunchControl.exe!invoke_thread_procedure(unsigned int(__stdcall*)(void *) procedure, void * const context) Line 92	 
LaunchControl.exe!thread_start<unsigned int (__stdcall*)(void *)>(void * const parameter) Line 115	 
[External Code]
```

Tested with very simple attitude control client with only four streams.

**Comment by djungelorm** [comment]
Should be fixed in this version:
https://krpc.s3.amazonaws.com/deploy/feature/stream-freezing/723.1/krpc-0.3.6-9-gb147c8e.zip

Multi-threaded code is so tricky to get right! :P

This version also includes the changes to make stream objects default and copy constructable.

**Comment by Assert1** [comment]
Looks like everyting works fine with this build. Now i can get a consistent state of vessel orbit, engines state and resources, this is very good thing. Thatnk you.

But the node creation problems still exists. I will make new issue about this later. I am expirienced a very strange things during and after node creation, something is realy wrong there. I do not know if this is a KSP, kRPC or other plugins issue, i need some time to ckeck.
